### ISSUE TITLE
Where are do Admin LTE folder for step 6 installation

### ISSUE THREAD

**Issue by guillebalmacedaonline** [goszowski/crud-generator-admin-lte#3]
Hi bro, where are do the admin lte folder for step 6. I do not see. Please help.

Publish config file & generator template files.

php artisan vendor:publish --provider="Goszowski\CrudGeneratorAdminLte\CrudGeneratorAdminLteServiceProvider::class"
Note: You should have configured database for this operation.

Copy the Admin LTE folder to public path and rename it to "admin-lte"

**Comment by goszowski** [comment]
You must download it from admin LTE website
